version: "3.8"

services:
  app:
    profiles: ["app"]
    restart: always
    container_name: migration-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 3000
    ports:
      - 3000:3000
    logging:
      driver: "local"
